id: I7992886B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:37:14+00:00'
last_modified: '2022-06-08T09:58:07.765689+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14607
  title: ཉམ་ཆུང་བུ་མོའི་ལས་དབང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    CECA:
      image_group_id: I4CZ354574
      title: ''
      total_pages: 294
      order: 1
      base_file: CECA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
