id: P009290
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14607
  title: ཉམ་ཆུང་བུ་མོའི་ལས་དབང་།
  author: ''
  volumes:
    7cd50e6e004b4cd9a0fdab9c44b4f6f3:
      image_group_id: I4CZ354574
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
